/* ADDRESS */
INSERT INTO PUBLIC.ADDRESS(CITY, STREET, NUMBER) VALUES('Lodz', 'Piotrkowska', '15');
INSERT INTO PUBLIC.ADDRESS(CITY, STREET, NUMBER) VALUES('Warszawa', 'Wiejska', '66');
INSERT INTO PUBLIC.ADDRESS(CITY, STREET, NUMBER) VALUES('Krakow', 'Podzamcze', '43');

/* EMPLOEYY */
INSERT INTO PUBLIC.EMPLOYEE(NAME, SURNAME, PASSWORD, EMAIL, CREATION_DATE, ACTIVE, ADDRESS_ID) VALUES ('Marek', 'Administrator', 'password', 'admin@o2.admin', '2017-09-14', '1', '1');

INSERT INTO PUBLIC.EMPLOYEE(NAME, SURNAME, PASSWORD, EMAIL, CREATION_DATE, ACTIVE, ADDRESS_ID) VALUES ('Marek', 'Developer', 'password', 'developer@o2.developer', '2017-09-12', '1', '2');

INSERT INTO PUBLIC.EMPLOYEE(NAME, SURNAME, PASSWORD, EMAIL, CREATION_DATE, ACTIVE, ADDRESS_ID) VALUES ('Marek', 'HumanResources', 'password', 'hr@o2.hr', '2017-09-11', '1', '3');

/* ADMIN */
INSERT INTO PUBLIC.ADMINISTRATOR(ADMINISTRATOR_ID) VALUES('1');

/* DEVELOPER */
INSERT INTO PUBLIC.DEVELOPER(DEVELOPER_ID) VALUES('2');

/* HR */
INSERT INTO PUBLIC.HUMAN_RESOURCE(HUMAN_RESOURCE_ID) VALUES('3');
